### ISSUE TITLE
GameMode abstract class or interface?

### ISSUE THREAD

**Issue by EliCDavis** [VideoGameDevClub/VacuumCleanSupreme#11]
Plans for the GameMode would make it an interface for people to implement their own game mode by filling out the definitions of the signatures provided by the interface to act as an event system.

With that said, adding a variety of signatures would allow people more control over the game mode they want to implement.  This is good except for the fact that every signature that is added to the interface **must** also be implemented in whatever class abides by the interface.

If we make the GameMode an abstract class filled with empty virtual methods to be overwritten by inheriting child classes, the child classes would not need to provide a definition for each method.

### Points to Discuss
1. Should we allow, when writing code, for a game mode to ignore an event?
  * Example: If there where an event like onVacuumBatteryConsumption(), should we allow a class to ignore providing a definition for it, because a battery might not be in it's game mode?
2.  Would providing a default definition for the event not be writing a default game mode?
3.  Should we force all game modes to implement signatures of a GameMode interface, even if those signatures might never be fired in the game?
  *  If there where an event like onVacuumBatteryConsumption() then the game mode would never spawn a battery.

**Comment by Blond-in-Blue** [comment]
What do you mean by "signature?" Is there any documentation related to this?

**Comment by hawkins** [comment]
I would include default behaviors.

**Comment by EliCDavis** [comment]
For those who are unfamiliar with interfaces,
### Interfaces
**An interface is a contract:** the guy writing the interface says, "hey, I accept things looking that way", and the guy using the interface says "Ok, the class I write looks that way".

**An interface is an empty shell**, there are only the *signatures* of the methods, which implies that the methods do not have a body. The interface can't do anything. It's just a pattern.

[A good description of the difference between the two](http://stackoverflow.com/questions/1913098/what-is-the-difference-between-an-interface-and-abstract-class)

**Comment by EliCDavis** [comment]
I think the best route would be to make GameMode an abstract class with alot of default behavior.  So much default behavior that most won't touch, but some might.  Such as OnBunnyInputLayTrap() will by default lay a trap, but an overloaded method might keep the bunny from laying a trap, or lay a battery, etc.
